# This workflow will install MicroPython and dependencies and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name:  Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - name: Install MicroPython
      run: |
        ./install-micropython.sh
    - name: Install Dependencies
      run: |
        git clone https://gitlab.com/alelec/micropython_unittest_junit.git /home/runner/.micropython/lib
    - name: Run Tests
      run: |
        micropython run_tests.py
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: "*.xml"